// ARRAY OF ALBUM INFO OBJECTS
simulations: [
    {
        albumId: "one",
        albumName: "Testing",
        albumTrackCount: 11, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_FrontCover.jpg",
        albumBackCover: "",
    },
    {
        albumId: "two",
        albumName: "Good Deeds And Synth",
        albumTrackCount: 6, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_BackCover.jpg",
    },
    {
        albumId: "three",
        albumName: "Instant Gratification",
        albumTrackCount: 26, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_BackCover.jpg",
    },
    {
        albumId: "four",
        albumName: "Micro dosing Fear",
        albumTrackCount: 9, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_BackCover.jpg",
    },
    {
        albumId: "five",
        albumName: "Alternate Immersion",
        albumTrackCount: 6, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_BackCover.jpg",
    },
    {
        albumId: "six",
        albumName: "Logical Eternity",
        albumTrackCount: 2, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s6_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s6_BackCover.jpg",
    },
    {
        albumId: "seven",
        albumName: "HitClips",
        albumTrackCount: 7, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_BackCover.jpg",
    },
    {
        albumId: "eight",
        albumName: "Lasouf",
        albumTrackCount: 0, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s8_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s8_BackCover.jpg",
    },
    {
        albumId: "nine",
        albumName: "Lorem Ipsum",
        albumTrackCount: 8, 
        albumDescription: "Blah Blah Blah",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_FrontCover.jpg",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_BackCover.jpg",
    },
    {
        albumId: "ten",
        albumFrontCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_FrontCover.png",
        albumBackCover: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_BackCover.png",
        albumName: "Plastic 604",
        albumTrackCount: 10, 
        albumDescription: "Blah Blah Blah",
    },
]