let app = {
    pages: [],
    show: new Event('show'),
    simulations: [
        {
          name: "Testing",
          trackCount: 11, 
          description: "Blah Blah Blah",
          
        },
        {
          name: "Good Deeds And Synth",
          trackCount: 6, 
          description: "Blah Blah Blah",
        },
        {
          name: "Instant Gratification",
          trackCount: 27, 
          description: "Blah Blah Blah",
        },
        {
          name: "Micro dosing Fear",
          trackCount: 9, 
          description: "Blah Blah Blah",
        },
        {
          name: "Alternate Immersion",
          trackCount: 6, 
          description: "Blah Blah Blah",
        },
        {
          name: "Logical Eternity",
          trackCount: 3, 
          description: "Blah Blah Blah",
        },
        {
          name: "HitClips",
          trackCount: 7, 
          description: "Blah Blah Blah",
        },
        {
          name: "Lasouf",
          trackCount: 0, 
          description: "Blah Blah Blah",
        },
        {
          name: "Lorem Ipsum",
          trackCount: 8, 
          description: "Blah Blah Blah",
        },
        {
          name: "Plastic 604",
          trackCount: 10, 
          description: "Blah Blah Blah",
        },
      ],
    trackList:[
        {
            trackName: "Achievement Unlocked: New Level Of Abstraction",
            trackSimNum: 1,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_1.mp3",
        },
        {
            trackName: "Dont Fight It And You Wont Get Hurt",
            trackSimNum: 1,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_2.mp3",
        },
        {
            trackName: "Just A Few More",
            trackSimNum: 1,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_3.mp3",
        },
        {
            trackName: "Dont Act Like You Dont See Me",
            trackSimNum: 1,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_4.mp3",
        },
        {
            trackName: "Oh So You Bboy Huh, Ok Lets Go",
            trackSimNum: 1,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_5.mp3",
        },
        {
            trackName: "There You Are",
            trackSimNum: 1,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_6.mp3",
        },
        {
            trackName: "Pretty People Malevolent Thoughts",
            trackSimNum: 1,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_7.mp3",
        },
        {
            trackName: "Balance",
            trackSimNum: 1,
            trackPosition: 8, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_8.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_8.mp3",
        },
        {
            trackName: "Electric",
            trackSimNum: 1,
            trackPosition: 9, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_9.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_9.mp3",
        },
        {
            trackName: "Locked In Memory And In Heart",
            trackSimNum: 1,
            trackPosition: 10, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_10.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_10.mp3",
        },
        {
            trackName: "Road Ends Ahead",
            trackSimNum: 1,
            trackPosition: 11, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s1_11.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s1_11.mp3",
        },
        {
            trackName: "Intro",
            trackSimNum: 2,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_1.mp3",
        },
        {
            trackName: "1",
            trackSimNum: 2,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_2.mp3",
        },
        {
            trackName: "2",
            trackSimNum: 2,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_3.mp3",
        },
        {
            trackName: "3",
            trackSimNum: 2,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_4.mp3",
        },
        {
            trackName: "4",
            trackSimNum: 2,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_5.mp3",
        },
        {
            trackName: "5",
            trackSimNum: 2,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s2_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s2_6.mp3",
        },
        {
            trackName: "Achievement Unlocked New Level Of Production",
            trackSimNum: 3,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_1.mp3",
        },
        {
            trackName: "I",
            trackSimNum: 3,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_2.mp3",
        },
        {
            trackName: "Oh My",
            trackSimNum: 3,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_3.mp3",
        },
        {
            trackName: "Montreal Scene",
            trackSimNum: 3,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_5.mp3",
        },
        {
            trackName: "Blue Dream",
            trackSimNum: 3,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_4.mp3",
        },
        {
            trackName: "Prince Of Darkness",
            trackSimNum: 3,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_5.mp3",
        },
        {
            trackName: "Jocker Tantrum",
            trackSimNum: 3,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_6.mp3",
        },
        {
            trackName: "I Never Got Why Youd Do That",
            trackSimNum: 3,
            trackPosition: 8, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_7.mp3",
        },
        {
            trackName: "Rabbit Hole",
            trackSimNum: 3,
            trackPosition: 9, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_8.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_8.mp3",
        },
        {
            trackName: "Conquering Vibe",
            trackSimNum: 3,
            trackPosition: 10, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_10.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_10.mp3",
        },
        {
            trackName: "Raised By The Internet",
            trackSimNum: 3,
            trackPosition: 11, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_11.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_11.mp3",
        },
        {
            trackName: "Past Present Future",
            trackSimNum: 3,
            trackPosition: 12, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_12.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_12.mp3",
        },
        {
            trackName: "Cathartic",
            trackSimNum: 3,
            trackPosition: 13, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_13.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_13.mp3",
        },
        {
            trackName: "Catacomb Vision",
            trackSimNum: 3,
            trackPosition: 14, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_14.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_14.mp3",
        },
        {
            trackName: "Wounded Hearts With Damaged Souls",
            trackSimNum: 3,
            trackPosition: 15, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_15.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_15.mp3",
        },
        {
            trackName: "Rhythm In The Beat",
            trackSimNum: 3,
            trackPosition: 16, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_16.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_16.mp3",
        },
        {
            trackName: "Time Travel Race Car",
            trackSimNum: 3,
            trackPosition: 17, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_17.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_17.mp3",
        },
        {
            trackName: "Truth To Passion",
            trackSimNum: 3,
            trackPosition: 18, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_18.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_18.mp3",
        },
        {
            trackName: "Fight Or Flight Which Do You Choose",
            trackSimNum: 3,
            trackPosition: 19, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_19.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_19.mp3",
        },
        {
            trackName: "Dummy Trap",
            trackSimNum: 3,
            trackPosition: 20, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_20.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_20.mp3",
        },
        {
            trackName: "Please Try Again Later",
            trackSimNum: 3,
            trackPosition: 21, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_21.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_21.mp3",
        },
        {
            trackName: "Dethroned",
            trackSimNum: 3,
            trackPosition: 21, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_21.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_21.mp3",
        },
        {
            trackName: "Where Is Earl",
            trackSimNum: 3,
            trackPosition: 23, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_23.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_23.mp3",
        },
        {
            trackName: "Good Morning",
            trackSimNum: 3,
            trackPosition: 24, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_24.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_24.mp3",
        },
        {
            trackName: "Soul Room",
            trackSimNum: 3,
            trackPosition: 25, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_25.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_25.mp3",
        },
        {
            trackName: "Demetreus Mathew Thomson",
            trackSimNum: 3,
            trackPosition: 26, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s3_26.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s3_26.mp3",
        },
        {
            trackName: "Why Are You Terrified",
            trackSimNum: 4,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_1.mp3",
        },
        {
            trackName: "I Cant Feel Enough",
            trackSimNum: 4,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_2.mp3",
        },
        {
            trackName: "Lord Forgive Me For I Have Sinned",
            trackSimNum: 4,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_3.mp3",
        },
        {
            trackName: "Lost In The Desert, Microdosing Fear",
            trackSimNum: 4,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_4.mp3",
        },
        {
            trackName: "Dancing Moral Trails",
            trackSimNum: 4,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_5.mp3",
        },
        {
            trackName: "Lost In The Amazon, Micro dosing Fear",
            trackSimNum: 4,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_6.mp3",
        },
        {
            trackName: "Clearing Clouds",
            trackSimNum: 4,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_7.mp3",
        },
        {
            trackName: "Merry Go Round",
            trackSimNum: 4,
            trackPosition: 8, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_8.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_8.mp3",
        },
        {
            trackName: "Young Dive In Chi",
            trackSimNum: 4,
            trackPosition: 9, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s4_9.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s4_9.mp3",
        },
        {
            trackName: "Shopping In The Early 2000s",
            trackSimNum: 5,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_1.mp3",
        },
        {
            trackName: "Walking To My Tesla To Swim With Whales",
            trackSimNum: 5,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_2.mp3",
        },
        {
            trackName: "Seen It Before",
            trackSimNum: 5,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_3.mp3",
        },
        {
            trackName: "97 To Billings Bridge",
            trackSimNum: 5,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_4.mp3",
        },
        {
            trackName: "You Pass Butter",
            trackSimNum: 5,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_5.mp3",
        },
        {
            trackName: "Burn Out",
            trackSimNum: 5,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s5_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s5_6.mp3",
        },
        {
            trackName: "Imminent Onus",
            trackSimNum: 6,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s6_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s6_1.mp3",
        },
        {
            trackName: "Ancient Philosophy",
            trackSimNum: 6,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s6_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s6_2.mp3",
        },
        {
            trackName: "DreamScape",
            trackSimNum: 7,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_1.mp3",
        },
        {
            trackName: "Felicia",
            trackSimNum: 7,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_2.mp3",
        },
        {
            trackName: "Nirvana",
            trackSimNum: 7,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_3.mp3",
        },
        {
            trackName: "NeverKnown",
            trackSimNum: 7,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_4.mp3",
        },
        {
            trackName: "Unknown",
            trackSimNum: 7,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_5.mp3",
        },
        {
            trackName: "Laughter",
            trackSimNum: 7,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_6.mp3",
        },
        {
            trackName: "Glitch",
            trackSimNum: 7,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s7_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s7_7.mp3",
        },
        {
            trackName: "What I Gotta Do To Play",
            trackSimNum: 9,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_1.mp3",
        },
        {
            trackName: "Bicycle For The Mind",
            trackSimNum: 9,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_2.mp3",
        },
        {
            trackName: "SoundCloud Gaara",
            trackSimNum: 9,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_3.mp3",
        },
        {
            trackName: "Defeat Your Own Mind",
            trackSimNum: 9,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_4.mp3",
        },
        {
            trackName: "Everydays Journey",
            trackSimNum: 9,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_5.mp3",
        },
        {
            trackName: "I Still Love You",
            trackSimNum: 9,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_6.mp3",
        },
        {
            trackName: "Selflish",
            trackSimNum: 9,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_7.mp3",
        },
        {
            trackName: "Jacuzzi On A Balcony",
            trackSimNum: 9,
            trackPosition: 8, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s9_8.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s9_8.mp3",
        },
        {
            trackName: "Front Street Boys",
            trackSimNum: 10,
            trackPosition: 1, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_1.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_1.mp3",
        },
        {
            trackName: "All Rise",
            trackSimNum: 10,
            trackPosition: 2, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_2.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_2.mp3",
        },
        {
            trackName: "Step Up",
            trackSimNum: 10,
            trackPosition: 3, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_3.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_3.mp3",
        },
        {
            trackName: "No You Never Thought",
            trackSimNum: 10,
            trackPosition: 4, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_4.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_4.mp3",
        },
        {
            trackName: "Sunday Night Train Freestyle",
            trackSimNum: 10,
            trackPosition: 5, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_5.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_5.mp3",
        },
        {
            trackName: "Lets Drive Away",
            trackSimNum: 10,
            trackPosition: 6, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_6.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_6.mp3",
        },
        {
            trackName: "Ostracized From Normality",
            trackSimNum: 10,
            trackPosition: 7, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_7.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_7.mp3",
        },
        {
            trackName: "Counterfeit Baby",
            trackSimNum: 10,
            trackPosition: 8, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_8.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_8.mp3",
        },
        {
            trackName: "Save Your Apologies",
            trackSimNum: 10,
            trackPosition: 9, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_9.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_9.mp3",
        },
        {
            trackName: "Youthful Apathy",
            trackSimNum: 10,
            trackPosition: 10, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_10.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_10.mp3",
        },
        {
            trackName: "Hit The Ground Hard",
            trackSimNum: 10,
            trackPosition: 11, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_11.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_11.mp3",
        },
        {
            trackName: "Encore That",
            trackSimNum: 10,
            trackPosition: 12, 
            trackDescription: "Blah Blah Blah",
            trackArt: "https://diveinchi-art.s3.us-east-2.amazonaws.com/s10_12.jpg",
            trackAudio: "https://diveinchi-tracks.s3.us-east-2.amazonaws.com/s10_12.mp3",
        },

        

    ],
    init: ()=>{
        console.log("after app.init")
        app.addListeners();
        app.pages = document.querySelectorAll('.page');
        app.pages.forEach((pg)=>{
            pg.addEventListener('show', app.pageShown);
        })
        document.querySelectorAll('.simButton').forEach((link)=>{
            link.addEventListener('click', app.nav);
        })
    },
    addListeners: ()=>{
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems, []);
    },
    nav: ev=>{
        ev.preventDefault();
        let btn = ev.target;
        let target = btn.getAttribute("data-target");
        console.log("Navigate to", target);
        document.querySelector(".page.active").classList.remove("active");
        document.getElementById(target).classList.add("active");
        app.buildSimulation(ev.target);
    },
    buildSimulation: tar =>{
        console.log('After buildSimulation');
        // let whatever = ev.target;
        console.log(tar.getAttribute('data-target'));

        let temp = document.getElementById('albumRow');
        let content = temp.content;
        let clone = content.cloneNode(true);
        document.getElementById("one").appendChild(clone);
        let img = clone.querySelector("trackArt");
        //loop through the simulation
        //what is the simulation number?
        //how many tracks are there?

        let uniqueEnd = "s"+simNum+"_"+trackNum+".jpg";
        img.src="https://diveinchi-art.s3.us-east-2.amazonaws.com/";
        //s10_BackCover.png
        //add this to src 
    },
}
const ready = "cordova" in window ? "deviceready" : "DOMContentLoaded";
document.addEventListener(ready, app.init);